package util;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class AlignmentGenerator {

	protected File referenceFile;
	List<File> vcfFiles = new ArrayList<File>();
	
	public AlignmentGenerator(File referenceFile) {
		this.referenceFile = referenceFile;
	}
	
	public void addVCFFile(File vcfFile) {
		if (vcfFile.exists() && vcfFile.getName().endsWith("vcf")) {
			vcfFiles.add(vcfFile);
		}
		else {
			throw new IllegalArgumentException("File " + vcfFile.getName() + " does not appear to be valid");
		}
	}
	
	//Need some sort of mutable sequence class that can emit bases, add in gaps and remove them, etc... 
	//...maybe then we just 'apply' a vcf or variant pool to the proto-sequence to obtain a mature sequence?
	//..then add in gaps generated by insertions in other sequences?
	
}
